import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import {db} from '../firebase'

export default function Home() {
  const [dogoneurl, setDogOneUrl] = useState("");
  const [dogtwourl, setDogTwoUrl] = useState("");
  const [dogonerating, setDogOneRating] = useState([]);
  const [dogtworating, setDogTwoRating] = useState([]);

  async function fetchDogsURL(){
    await fetch("https://dog.ceo/api/breeds/image/random", {
      method: "GET",
    }).then((res) => res.json())
    .then((result) => {
      setDogOneUrl(result.message);
    });
    await fetch("https://dog.ceo/api/breeds/image/random", {
      method: "GET",
    }).then((res) => res.json())
    .then((result) => {
      setDogTwoUrl(result.message);
    });
    try {
      const dogDataOne = {
        id: dogoneurl.substring(30, dogoneurl.length-4).replace('/', ''),
        rating: 200,
      }
      const dogDataTwo = {
        id: dogtwourl.substring(30, dogtwourl.length-4).replace('/', ''),
        rating: 200,
      }
      console.log(dogDataOne.id)
      db.collection("dogs")
      .doc(dogDataOne.id)
      .get()
      .then((doc) => {
        if (doc.exists) {
          setDogOneRating(doc.data().rating)
        } else {
          const docRef = db.collection("dogs").doc(dogDataOne.id);
          docRef
            .set(dogDataOne)
            .then(() => {
              console.log("Document successfully written!");
            })
            .catch((error) => {
              console.error("Error writing document: ", error);
            });
          setDogOneRating(200)

        }
      })
      db.collection("dogs")
      .doc(dogDataTwo.id)
      .get()
      .then((doc) => {
        if (doc.exists) {
          console.log("Document exists:", doc.data());
        } else {
          const docRef = db.collection("dogs").doc(dogDataTwo.id);
          docRef
            .set(dogDataTwo)
            .then(() => {
              console.log("Document successfully written!");
              setDogTwoRating(doc.data().rating)
            })
            .catch((error) => {
              console.error("Error writing document: ", error);
            });

          setDogTwoRating(200)

        }
      })
      .catch((error) => {
        console.error("Error checking document:", error);
      });
     

    } catch (error) {
        console.error('Error adding comment:', error);
    }
    // window.location.reload()
  }
  async function dogoneclick(){
    let p = (1.0 * 1.0) / (1 + 1.0 * Math.pow(10, (1.0 * (dogonerating - dogtworating)) / 400))
    const dogDataOne = {
      id: dogoneurl.substring(30, dogoneurl.length-4).replace('/', ''),
      rating: dogonerating + 24 * (1 - p),
    }
    const dogDataTwo = {
      id: dogtwourl.substring(30, dogtwourl.length-4).replace('/', ''),
      rating: dogtworating + 24 * (0 - p),
    }
    const docRefOne = db.collection("dogs").doc(dogDataOne.id);
    docRefOne
      .set(dogDataOne, { merge: true })
      .then(() => {
        console.log("Document successfully updated!");
      })
      .catch((error) => {
        console.error("Error updating document: ", error);
      });
    const docRefTwo = db.collection("dogs").doc(dogDataTwo.id);
    docRefTwo
      .set(dogDataTwo, { merge: true })
      .then(() => {
        console.log("Document successfully updated!");
      })
      .catch((error) => {
        console.error("Error updating document: ", error);
      });

      window.location.reload();    
    }
  return (
    <div>
      <Head>
        <title>🐶 Dogmash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className=''>
        <h1>🐶Dogmash!!</h1>
        <h3>Whether you like <i>dogs</i> or hot <i>dogs</i>, this website is for you.</h3>
        <div>
          <button onClick={dogoneclick} class="dog">
            <Image width="300" height="300" src={dogoneurl}></Image>
            <h2>Dog #1</h2>
          </button>
          <button class="dog">
            <Image width="300" height="300" src={dogtwourl}></Image>
            <h2>Dog #2</h2>
          </button>
        </div>
        <button onClick={fetchDogsURL}>Fetch!</button>

      </div>
      <h3 className='pt-[50rem]'>Made by <a href="https://github.com/kach0w">kach0w</a></h3>
    </div>
  )
}
